version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - nest-app
      - node-app
    volumes:
      - ./apps/nginx-app/nginx.conf:/etc/nginx/nginx.conf
  node-app:
    build:
      context: ./apps/node-app
      dockerfile: Dockerfile
    ports:
      - "3007:3000" # host port: container port
    volumes:
      - ./apps/node-app:/app # host directory path: container directory path
      - /app/node_modules
      - ~/.config/nvim:/root/.config/nvim
    environment:
      - NODE_ENV=development

  nest-app:
    build:
      context: ./apps/nest-app
      dockerfile: Dockerfile
    ports:
      - "3006:3000" # host's port :container's port
    volumes:
      - ./apps/nest-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
