version: "3.9"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - nest-app
      - node-app
    volumes:
      - ./apps/nginx-app/nginx.conf:/etc/nginx/nginx.conf

  node-db:
    image: postgres:15.3
    restart: always
    container_name: node-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: -p ${DB_PORT}
    ports:
      - ${DB_MAP_PORT}:${DB_PORT}
    env_file:
      - .env
    volumes:
      - node-db:/var/lib/postgresql/data
      - ./scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  node-app:
    build:
      context: ./apps/node-app
      dockerfile: Dockerfile
    ports:
      - "3007:3000"
    volumes:
      - ./apps/node-app:/app
      - /app/node_modules
      - ~/.config/nvim:/root/.config/nvim
    environment:
      - NODE_ENV=development
  db-node:
    image: postgres:15
    environment:
      POSTGRES_USER: nodeUser
      POSTGRES_PASSWORD: nodePassword
      POSTGRES_DB: nodeDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nest-app:
    build:
      context: ./apps/nest-app
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
    volumes:
      - ./apps/nest-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  db-nest:
    image: postgres:15
    environment:
      POSTGRES_USER: nestUser
      POSTGRES_PASSWORD: nestPassword
      POSTGRES_DB: nestDatabase
    ports:
      - "5433:5432" #host: container
    volumes:
      - postgres-data:/var/lib/postgresql/data
